### ISSUE TITLE
Research the use of Adaptive Cards for the Bot Framework & FB Messenger

### ISSUE THREAD

**Issue by m4thfr34k** [AmericanRedCross/damage-assessment-bot#96]

**Comment by blueelvis** [comment]
Adaptive cards are not going to work properly the way we want with Facebook since they are down rendered. This means that any buttons which are presented as part of the Adaptive Card will not work.

Source -- https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-media-attachments?view=azure-bot-service-4.0&tabs=csharp#send-an-adaptive-card
